package fr.nargit.gradle;

import fr.nargit.rating.algorihtm.elo.EloAlgorithm;
import fr.nargit.rating.algorihtm.elo.performance.SimpleEloPerformance;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
	public static void main(String[] args) {
		EloAlgorithm eloAlgorithm = new EloAlgorithm(new SimpleEloPerformance());

		double winnerElo =
				eloAlgorithm.calculateNewQuotation(1000, 1000, 1, 20);
		double looserElo =
				eloAlgorithm.calculateNewQuotation(1000, 1000, 2, 20);

		System.out.println(String.format("Winner elo %f", winnerElo));
		System.out.println(String.format("Winner elo %f", looserElo));
	}
}
